// Ability definitions — rewritten wholesale by the EDITOR on the
// main menu. Values survive a round trip; comments and formatting inside the
// array below do not, so keep notes in the schema file instead.
// Shapes, cooldown scaling and costs are explained in ../abilities.js.

export const ABILITIES = [
  {
    id: 'punch',
    label: 'Punch',
    target: 'melee',
    range: 1.6,
    arc: 90,
    castTime: 0.05,
    castSlow: 0.8,
    cooldown: 0.7,
    cooldownRate: 'attackSpeed',
    costAttribute: '',
    cost: 0,
    effects: [{ effect: 'hit', to: 'target' }],
  },
  {
    id: 'basicAttack',
    label: 'Swing',
    target: 'melee',
    range: 3,
    arc: 120,
    castTime: 0.1,
    castSlow: 0.5,
    cooldown: 1,
    cooldownRate: 'attackSpeed',
    costAttribute: 'health',
    cost: 5,
    effects: [{ effect: 'hit', to: 'target' }],
    castTurn: 720,
    vfx: 'effect3',
  },
  {
    id: 'bolt',
    label: 'Bolt',
    target: 'projectile',
    range: 9,
    speed: 12,
    size: 0.18,
    castTime: 0.5,
    castSlow: 0.85,
    cooldown: 0.65,
    cooldownRate: '',
    costAttribute: '',
    cost: 0,
    effects: [{ effect: 'hit', to: 'target' }],
    trail: 'campfire',
  },
  {
    id: 'gruntSwipe',
    label: 'Swipe',
    target: 'melee',
    range: 0.65,
    arc: 180,
    castTime: 0.1,
    castSlow: 0.5,
    cooldown: 1,
    cooldownRate: 'attackSpeed',
    costAttribute: '',
    cost: 0,
    effects: [{ effect: 'hit', to: 'target' }],
  },
  {
    id: 'bruteSlam',
    label: 'Slam',
    target: 'melee',
    range: 3,
    arc: 360,
    castTime: 0.1,
    castSlow: 0.5,
    cooldown: 1,
    cooldownRate: 'attackSpeed',
    costAttribute: '',
    cost: 0,
    effects: [{ effect: 'hit', to: 'target' }],
  },
  {
    id: 'swordCombo',
    label: 'Sword',
    target: 'combo',
    steps: ['basicAttack', 'gruntSwipe', 'bruteSlam'],
    chainWindow: 5,
    cooldown: 5,
    cooldownRate: 'attackSpeed',
    costAttribute: '',
    cost: 0,
    effects: [],
    stepGap: 0.2,
  },
  {
    id: 'dash',
    label: 'Dash',
    target: 'dash',
    range: 3,
    speed: 30,
    aimedBy: 'cursor',
    castTime: 0,
    castSlow: 1,
    cooldown: 1,
    cooldownRate: '',
    costAttribute: '',
    cost: 0,
    effects: [],
    interrupts: true,
  },
  {
    id: 'handgun',
    label: 'Hand Gun',
    target: 'projectile',
    range: 10,
    arc: 120,
    aimedBy: 'cursor',
    castTime: 0,
    castSlow: 0.5,
    cooldown: 1,
    cooldownRate: 'attackSpeed',
    costAttribute: '',
    cost: 0,
    effects: [],
    size: 0.1,
    trail: 'effect',
  },
];
