// Asset definitions — rewritten wholesale by the EDITOR on the
// main menu. Values survive a round trip; comments and formatting inside the
// array below do not, so keep notes in the schema file instead.
// The files themselves are in ../assets/; the shape is in ../../../Engine/src/data/assets.js.

export const ASSETS = [
  {
    id: 'asset2',
    label: 'wood',
    kind: 'texture',
    file: 'wood.png',
    uScale: 1,
    vScale: 1,
    uOffset: 0,
    vOffset: 0,
    transparent: false,
  },
  {
    id: 'asset7',
    label: 'sand-diffuse',
    kind: 'texture',
    file: 'Sand_base_color.png',
    uScale: 1,
    vScale: 1,
    uOffset: 0,
    vOffset: 0,
    transparent: false,
  },
  {
    id: 'sandNormal',
    label: 'sand_normal',
    kind: 'texture',
    file: 'Sand_normal.png',
    uScale: 1,
    vScale: 1,
    uOffset: 0,
    vOffset: 0,
    transparent: false,
  },
  {
    id: 'blockCorner',
    label: 'block-corner',
    kind: 'mesh',
    file: 'block-corner.glb',
    scale: 1,
    rotX: 0,
    rotY: 0,
    rotZ: 0,
    lift: 0.5,
  },
  {
    id: 'blockMid',
    label: 'block-mid',
    kind: 'mesh',
    file: 'block-mid.glb',
    scale: 1,
    rotX: 0,
    rotY: 0,
    rotZ: 0,
    lift: 0.5,
  },
  {
    id: 'blockSide',
    label: 'block-side',
    kind: 'mesh',
    file: 'block-side.glb',
    scale: 1,
    rotX: 0,
    rotY: 0,
    rotZ: 0,
    lift: 0.5,
  },
  {
    id: 'grassBaseColor',
    label: 'Grass_base_color',
    kind: 'texture',
    file: 'Grass_base_color.png',
    uScale: 1,
    vScale: 1,
    uOffset: 0,
    vOffset: 0,
    transparent: false,
  },
  {
    id: 'grassNormal',
    label: 'Grass_normal',
    kind: 'texture',
    file: 'Grass_normal.png',
    uScale: 1,
    vScale: 1,
    uOffset: 0,
    vOffset: 0,
    transparent: false,
  },
  {
    id: 'grassSandBaseColor',
    label: 'Grass-Sand_base_color',
    kind: 'texture',
    file: 'Grass-Sand_base_color.png',
    uScale: 1,
    vScale: 1,
    uOffset: 0,
    vOffset: 0,
    transparent: false,
  },
  {
    id: 'grassSandNormal',
    label: 'Grass-Sand_normal',
    kind: 'texture',
    file: 'Grass-Sand_normal.png',
    uScale: 1,
    vScale: 1,
    uOffset: 0,
    vOffset: 0,
    transparent: false,
  },
  {
    id: 'grassSandCornerBaseColor',
    label: 'Grass-Sand-corner_base_color',
    kind: 'texture',
    file: 'Grass-Sand-corner_base_color.png',
    uScale: 1,
    vScale: 1,
    uOffset: 0,
    vOffset: 0,
    transparent: false,
  },
  {
    id: 'grassSandCornerNormal',
    label: 'Grass-Sand-corner_normal',
    kind: 'texture',
    file: 'Grass-Sand-corner_normal.png',
    uScale: 1,
    vScale: 1,
    uOffset: 0,
    vOffset: 0,
    transparent: false,
  },
  {
    id: 'testBaseColor',
    label: 'Test_base_color',
    kind: 'texture',
    file: 'Test_base_color.png',
    uScale: 1,
    vScale: 1,
    uOffset: 0,
    vOffset: 0,
    transparent: false,
  },
  {
    id: 'testNormal',
    label: 'Test_normal',
    kind: 'texture',
    file: 'Test_normal.png',
    uScale: 1,
    vScale: 1,
    uOffset: 0,
    vOffset: 0,
    transparent: false,
  },
];
