// Material definitions — rewritten wholesale by the EDITOR on the
// main menu. Values survive a round trip; comments and formatting inside the
// array below do not, so keep notes in the schema file instead.
// Named surfaces; the shape is in ../../../Engine/src/data/materials.js.

export const MATERIALS = [
  {
    id: 'material',
    label: 'material',
    texture: 'testBaseColor',
    bump: 'testNormal',
    color: 16767626,
    uScale: 1,
    vScale: 1,
    uOffset: 0,
    vOffset: 0,
    roughness: 0.78,
    metallic: 0.75,
    bumpStrength: 1,
    emissive: 0,
    emissiveStrength: 0,
    alpha: 1,
    transparent: false,
    backFaces: false,
    unlit: false,
  },
  {
    id: 'material2',
    label: 'sand',
    texture: 'asset7',
    bump: 'sandNormal',
    color: 16777215,
    uScale: 1,
    vScale: 1,
    uOffset: 0,
    vOffset: 0,
    roughness: 0.74,
    metallic: 0.54,
    bumpStrength: 0.25,
    emissive: 13802577,
    emissiveStrength: 0,
    alpha: 1,
    transparent: false,
    backFaces: false,
    unlit: false,
  },
  {
    id: 'material3',
    label: 'grass',
    texture: 'grassBaseColor',
    bump: 'grassNormal',
    color: 16777215,
    uScale: 1,
    vScale: 1,
    uOffset: 0,
    vOffset: 0,
    roughness: 0.8,
    metallic: 0,
    bumpStrength: 0.25,
    emissive: 0,
    emissiveStrength: 0,
    alpha: 1,
    transparent: false,
    backFaces: false,
    unlit: false,
  },
  {
    id: 'material4',
    label: 'grass-sand',
    texture: 'grassSandBaseColor',
    bump: 'grassSandNormal',
    color: 16777215,
    uScale: 1,
    vScale: 1,
    uOffset: 0,
    vOffset: 0,
    roughness: 0.8,
    metallic: 0,
    bumpStrength: 1,
    emissive: 0,
    emissiveStrength: 0,
    alpha: 1,
    transparent: false,
    backFaces: false,
    unlit: false,
  },
  {
    id: 'material5',
    label: 'grass-sand-corner',
    texture: 'grassSandCornerBaseColor',
    bump: 'grassSandCornerNormal',
    color: 16777215,
    uScale: 1,
    vScale: 1,
    uOffset: 0,
    vOffset: 0,
    roughness: 0.8,
    metallic: 0,
    bumpStrength: 0.25,
    emissive: 0,
    emissiveStrength: 0,
    alpha: 1,
    transparent: false,
    backFaces: false,
    unlit: false,
  },
];
